In [3]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine("postgresql+psycopg://bonds:bonds@localhost:5418/bonds")

In [12]:
df = pd.read_sql('''
select * from securities where instrument_type in ('GSEC', 'SDL')
''', eng)

In [13]:
df.head()

,isin,instrument_type,description,issuer,coupon,maturity_date,face_value,source,first_seen,last_seen,created_at,updated_at,interest_type
0,IN1520110082,SDL,08.88 GJ SDL 2021,State Government (GJ),8.88,2021-10-05,100.0,fbil,2021-03-16,2026-07-18,2026-07-18 14:16:45.315320+00:00,2026-07-18 14:16:45.315320+00:00,FIXED
1,IN2220110059,SDL,08.89 MH SDL 2021,State Government (MH),8.89,2021-10-05,100.0,fbil,2021-03-16,2026-07-18,2026-07-18 14:16:45.315320+00:00,2026-07-18 14:16:45.315320+00:00,FIXED
2,IN1020110079,SDL,08.90 AP SDL 2021,State Government (AP),8.90,2021-10-05,100.0,fbil,2021-03-16,2026-07-18,2026-07-18 14:16:45.315320+00:00,2026-07-18 14:16:45.315320+00:00,FIXED
3,IN2120200042,SDL,05.73 MP SDL 2021,State Government (MP),5.73,2021-10-08,100.0,fbil,2021-03-16,2026-07-18,2026-07-18 14:16:45.315320+00:00,2026-07-18 14:16:45.315320+00:00,FIXED
4,IN2820110111,SDL,08.98 PN SDL 2021,State Government (PN),8.98,2021-10-14,100.0,fbil,2021-03-16,2026-07-18,2026-07-18 14:16:45.315320+00:00,2026-07-18 14:16:45.315320+00:00,FIXED

In [11]:
pd.read_sql('select distinct  instrument_type from securities', eng)

  instrument_type
0            CORP
1            GSEC
2             SDL
3             SGB
4          STRIPS
5           TBILL